// Single source of truth for all product pages and the selection grid.

export const products = [
  {
    slug: 'wagyu-reserve',
    title: 'Wagyu Reserve',
    category: 'Beef',
    categorySlug: 'beef',
    cats: ['beef'],
    tagline: 'Beef · Dry-Aged · Reserve',
    price: '$280',
    unit: 'per lb',
    image: 'https://images.unsplash.com/photo-1615937691194-97dbd3f3dc29?w=1600&q=80',
    cardTags: ['Beef', 'Dry-Aged'],
    cardSpan: 'wide',
    description: [
      'The summit of beef. Imported direct from a single producer in Miyazaki Prefecture, this is A5 Japanese Wagyu graded BMS 11–12 — the marbling so fine it reads like lace through the muscle.',
      'We portion it ourselves, by hand, into 8-ounce striploin steaks. The fat melts at body temperature; the texture is closer to silk than to beef. Cook hot and fast in a dry pan; salt at the table.',
    ],
    specs: [
      ['Origin', 'Miyazaki Prefecture, Japan'],
      ['Grade', 'A5 · BMS 11–12'],
      ['Cut', 'Striploin · 8 oz portion'],
      ['Age', '28 days · dry-aged on site'],
      ['Cook', 'Sear hot, rest twice the cooking time'],
    ],
    related: ['dry-aged-ribeye', 'tomahawk', 'wagyu-brisket', 'the-board'],
  },
  {
    slug: 'dry-aged-ribeye',
    title: 'Dry-Aged Ribeye',
    category: 'Beef',
    categorySlug: 'beef',
    cats: ['beef'],
    tagline: 'Beef · Dry-Aged 45 Days',
    price: '$68',
    unit: 'per lb',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuBUoAyp3pZW4V7HHKR6YBm9ceK7-blqFATg&s',
    cardTags: ['Beef'],
    description: [
      'Grass-fed beef from a regenerative herd in the Cotswold hills, hung on our salt-room hooks for forty-five days. The fat turns butter-yellow; the lean grows mineral and deep.',
      'Cut bone-in to twelve ounces, with the full eye and the spinalis cap intact. The cap is where the singing happens. Cook over real heat, rest long, slice across the grain.',
    ],
    specs: [
      ['Origin', 'Cotswold Hills, England'],
      ['Breed', 'Hereford / Aberdeen Angus'],
      ['Cut', 'Bone-in ribeye · 12 oz'],
      ['Age', '45 days · dry-aged on site'],
      ['Cook', 'High heat, rest 10 minutes'],
    ],
    related: ['wagyu-reserve', 'tomahawk', 'wagyu-brisket', 'spring-lamb'],
  },
  {
    slug: 'tomahawk',
    title: 'The Tomahawk',
    category: 'Beef',
    categorySlug: 'beef',
    cats: ['beef'],
    tagline: 'Beef · Bone-in · Showpiece',
    price: '$58',
    unit: 'per lb',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBDKE8laYmEG_xqCWdOWIudfyjsLeyVpV2eA&s',
    cardTags: ['Beef'],
    description: [
      'A ribeye on its full long rib, French-trimmed by hand until the bone gleams. Thirty-six ounces, more or less, depending on the animal — a cut built for the centre of the table.',
      'Best cooked over coals or hardwood, basted with rendered fat and finished in butter. The bone insulates the lean and gives the room something to look at while you carve.',
    ],
    specs: [
      ['Origin', 'Northumberland, England'],
      ['Cut', 'Bone-in ribeye · ~36 oz'],
      ['Age', '35 days · dry-aged on site'],
      ['Serves', 'Two, generously'],
      ['Cook', 'Live fire, basted, rested 12 min'],
    ],
    related: ['dry-aged-ribeye', 'wagyu-reserve', 'wagyu-brisket', 'spring-lamb'],
  },
  {
    slug: 'heritage-berkshire',
    title: 'Heritage Berkshire',
    category: 'Pork',
    categorySlug: 'pork',
    cats: ['pork'],
    tagline: 'Pork · Heritage Breed',
    price: '$32',
    unit: 'per lb',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7WabZEyAYsDypjHYvabU-A2qxyoF9-5t1gQ&s',
    cardTags: ['Pork'],
    description: [
      'Pure-bred Berkshire pork from a small Hampshire farm. Slow-grown to fifteen months on a forage diet of acorns, apples and grass, the flesh is darker than commodity pork and has the marbling of good beef.',
      'Available as bone-in chops, whole loin, or pieces cut to your specification. The fat takes seasoning beautifully and renders to a deep amber. Cook to 60°C and let it rest.',
    ],
    specs: [
      ['Origin', 'Hampshire, England'],
      ['Breed', 'Pure Berkshire'],
      ['Cut', 'Bone-in chop · 10 oz'],
      ['Age', '15 months'],
      ['Cook', 'Medium heat, rest 5 min'],
    ],
    related: ['iberico-bellota', 'slow-cured-belly', 'the-board', 'wagyu-reserve'],
  },
  {
    slug: 'iberico-bellota',
    title: 'Iberico Bellota',
    category: 'Charcuterie',
    categorySlug: 'charcuterie',
    cats: ['pork', 'charcuterie'],
    tagline: 'Pork · Acorn-Finished · Cured 36 months',
    price: '$145',
    unit: 'per lb',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOaw0qWNt4A1_Eaq8wqOymLFjvLIQYD9SScg&s',
    cardTags: ['Pork', 'Charcuterie'],
    description: [
      'Hand-sliced from a single 100% pure Iberico leg, finished on acorns in the Dehesa oak forests of Extremadura. The fat is so unsaturated it melts at hand-warmth and the flavour is impossibly nutty.',
      'We carve it to order in eighty-gram portions. Let the slices come to room temperature for ten minutes before eating; the fat needs to relax. Eat on its own; do not improve it.',
    ],
    specs: [
      ['Origin', 'Extremadura, Spain'],
      ['Breed', '100% pure Iberico'],
      ['Cure', '36 months in the cellar'],
      ['Diet', 'Acorn-finished (bellota)'],
      ['Serve', 'Room temperature, hand-carved'],
    ],
    related: ['the-board', 'heritage-berkshire', 'slow-cured-belly', 'duck-breast'],
  },
  {
    slug: 'slow-cured-belly',
    title: 'Slow-Cured Belly',
    category: 'Pork',
    categorySlug: 'pork',
    cats: ['pork'],
    tagline: 'Pork · 14-Day Cure',
    price: '$28',
    unit: 'per lb',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsDZ8FFs3MzVE9g0ceEJMnCsAuctNnmXtC9g&s',
    cardTags: ['Pork'],
    cardSpan: 'wide',
    description: [
      'Heritage Berkshire belly cured in our own dry rub of sea salt, raw cane sugar, juniper and black pepper for fourteen days. We rinse, dry, and rest it for another two days before it goes to the counter.',
      'Slice thick for braises, thin for the pan. The fat layers crisp at the edges and remain silken in the middle. The cure does the seasoning for you. Taste before adding salt.',
    ],
    specs: [
      ['Origin', 'Hampshire, England'],
      ['Cure', '14 days · house dry rub'],
      ['Cut', 'Boneless belly · 1 kg piece'],
      ['Keep', 'Refrigerated, 10 days'],
      ['Cook', 'Low oven 140°C for 3 hours'],
    ],
    related: ['heritage-berkshire', 'iberico-bellota', 'the-board', 'lamb-shoulder'],
  },
  {
    slug: 'spring-lamb',
    title: 'Spring Lamb',
    category: 'Lamb',
    categorySlug: 'lamb',
    cats: ['lamb'],
    tagline: 'Lamb · Grass-Fed · Seasonal',
    price: '$44',
    unit: 'per lb',
    image: 'https://images.unsplash.com/photo-1766589152317-fd811dd44c65?w=1600&q=80',
    cardTags: ['Lamb', 'Grass-Fed'],
    cardSpan: 'wide',
    description: [
      'Milk-fed lamb from a flock in the Welsh hills, brought in only between April and July. The meat is pale, delicately flavoured, and the fat has the faint sweetness only spring grass produces.',
      'We offer the rack frenched, the loin boned and rolled, or the whole saddle. Roast hot and fast to medium-rare; the lamb does not want to be hurried but it does not want to be punished, either.',
    ],
    specs: [
      ['Origin', 'Brecon Beacons, Wales'],
      ['Season', 'April to July'],
      ['Cut', 'Rack · 8 bones, frenched'],
      ['Diet', "Mother's milk + spring grass"],
      ['Cook', 'Hot oven, rest 8 min'],
    ],
    related: ['lamb-shoulder', 'dry-aged-ribeye', 'free-range-bird', 'heritage-berkshire'],
  },
  {
    slug: 'lamb-shoulder',
    title: 'Lamb Shoulder',
    category: 'Lamb',
    categorySlug: 'lamb',
    cats: ['lamb'],
    tagline: 'Lamb · Slow-Cook Cut',
    price: '$24',
    unit: 'per lb',
    image: 'https://images.unsplash.com/photo-1625604087024-7fb428fc4626?w=800&q=80',
    cardTags: ['Lamb'],
    description: [
      'The hard-working muscle of the lamb, bone-in and well-marbled. Hours in a low oven and it falls apart at the touch of a spoon. The fat dissolves into the meat, the bone gives up its marrow.',
      'A whole shoulder feeds four to six. Rub with garlic, anchovy and rosemary; cook covered at 130°C for five hours, then uncover for the last thirty minutes for the crust.',
    ],
    specs: [
      ['Origin', 'Yorkshire Dales, England'],
      ['Cut', 'Bone-in shoulder · ~2 kg'],
      ['Diet', 'Pasture-raised, grass-finished'],
      ['Serves', '4 to 6'],
      ['Cook', 'Low oven 130°C for 5 hours'],
    ],
    related: ['spring-lamb', 'slow-cured-belly', 'free-range-bird', 'heritage-berkshire'],
  },
  {
    slug: 'free-range-bird',
    title: 'Free-Range Bird',
    category: 'Poultry',
    categorySlug: 'poultry',
    cats: ['poultry'],
    tagline: 'Poultry · Pasture-Raised',
    price: '$18',
    unit: 'per lb',
    image: 'https://images.unsplash.com/photo-1606728035253-49e8a23146de?w=800&q=80',
    cardTags: ['Poultry'],
    description: [
      'A proper chicken, not a factory-grown one. Pasture-raised on a Suffolk farm, slow-grown to twelve weeks, with the firm flesh and deep yellow fat of a bird that walked for its dinner.',
      'Whole birds with feet and giblets intact for stock-making. We spatchcock to order. Brine for six hours, roast at 200°C breast-down for the first half, breast-up for the second.',
    ],
    specs: [
      ['Origin', 'Suffolk, England'],
      ['Breed', 'Sasso heritage cross'],
      ['Weight', '1.8 to 2.2 kg whole'],
      ['Age at slaughter', '12 weeks'],
      ['Cook', 'Roast 200°C, total ~1 hour'],
    ],
    related: ['duck-breast', 'spring-lamb', 'lamb-shoulder', 'heritage-berkshire'],
  },
  {
    slug: 'duck-breast',
    title: 'Duck Breast',
    category: 'Poultry',
    categorySlug: 'poultry',
    cats: ['poultry'],
    tagline: 'Poultry · Magret',
    price: '$28',
    unit: 'per lb',
    image: 'https://images.unsplash.com/photo-1582391123232-6130296f1fcd?w=800&q=80',
    cardTags: ['Poultry'],
    description: [
      'Magret from Gascon ducks raised for the table, with a thick, well-developed fat cap and dark, beefy flesh. Score the skin in a tight crosshatch and start in a cold dry pan, skin-side down.',
      'The fat renders out; the skin crisps; the flesh stays rosy. Eight to ten minutes on the skin, two on the flesh, ten of rest. Save the rendered fat for potatoes.',
    ],
    specs: [
      ['Origin', 'Gascony, France'],
      ['Breed', 'Mulard'],
      ['Cut', 'Magret · ~12 oz'],
      ['Score', 'Crosshatch, skin only'],
      ['Cook', 'Cold pan, skin-down, 8 min'],
    ],
    related: ['free-range-bird', 'iberico-bellota', 'the-board', 'wagyu-reserve'],
  },
  {
    slug: 'wagyu-brisket',
    title: 'Wagyu Brisket',
    category: 'Beef',
    categorySlug: 'beef',
    cats: ['beef'],
    tagline: 'Beef · Low and Slow',
    price: '$52',
    unit: 'per lb',
    image: 'https://images.unsplash.com/photo-1623174025518-b49000fb653d?w=800&q=80',
    cardTags: ['Beef'],
    description: [
      'A whole packer brisket from a Wagyu-cross herd in Yorkshire. The point and flat together — eight to ten pounds of marbled muscle built for fourteen hours in the smoker.',
      'We trim it for you to a quarter-inch fat cap, leaving the seam fat in place. Salt and pepper is all it needs. Cook to an internal probe-tender of 92°C, rest in a cooler for two hours.',
    ],
    specs: [
      ['Origin', 'Yorkshire, England'],
      ['Breed', 'Wagyu × Angus'],
      ['Cut', 'Whole packer · 4 to 5 kg'],
      ['Trim', '1/4 inch fat cap, seam intact'],
      ['Cook', 'Smoke at 110°C, 12 to 14 hours'],
    ],
    related: ['dry-aged-ribeye', 'wagyu-reserve', 'tomahawk', 'slow-cured-belly'],
  },
  {
    slug: 'the-board',
    title: 'The Board',
    category: 'Charcuterie',
    categorySlug: 'charcuterie',
    cats: ['charcuterie'],
    tagline: 'Charcuterie · House-Cured · Serves 4',
    price: '$86',
    unit: 'per board',
    image: 'https://images.unsplash.com/photo-1606851094291-6efae152bb87?w=1600&q=80',
    cardTags: ['Charcuterie', 'House-Cured'],
    cardSpan: 'wide',
    description: [
      "A curated selection of our house cures and one or two guest items from makers we trust. Iberico de bellota, fennel salami, coppa, our duck rillettes, and the cellar's current pickle.",
      "We build each board the morning of pickup. Tell us if you'd like it leaner or richer, and we'll adjust. Comes with sourdough crackers, mustard, and quince paste.",
    ],
    specs: [
      ['Composition', '5 cured meats · 2 condiments'],
      ['Serves', '4 generously'],
      ['Cures', 'All in-house except where noted'],
      ['Order', '24 hours ahead'],
      ['Keep', 'Best within 6 hours of pickup'],
    ],
    related: ['iberico-bellota', 'slow-cured-belly', 'duck-breast', 'heritage-berkshire'],
  },
];

export function getProduct(slug) {
  return products.find((p) => p.slug === slug);
}

export function getRelated(product) {
  return (product.related || [])
    .map((slug) => products.find((p) => p.slug === slug))
    .filter(Boolean);
}

export const CATEGORIES = [
  { slug: 'all', label: 'All' },
  { slug: 'beef', label: 'Beef' },
  { slug: 'pork', label: 'Pork' },
  { slug: 'lamb', label: 'Lamb' },
  { slug: 'poultry', label: 'Poultry' },
  { slug: 'charcuterie', label: 'Charcuterie' },
];
